package hu.blackbelt.judo.runtime.core.security;

/*-
 * #%L
 * JUDO Runtime Core :: Security
 * %%
 * Copyright (C) 2018 - 2023 BlackBelt Technology
 * %%
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * http://www.eclipse.org/legal/epl-2.0.
 *
 * This Source Code may also be made available under the following Secondary
 * Licenses when the conditions for such availability set forth in the Eclipse
 * Public License, v. 2.0 are satisfied: GNU General Public License, version 2
 * with the GNU Classpath Exception which is
 * available at https://www.gnu.org/software/classpath/license.html.
 *
 * SPDX-License-Identifier: EPL-2.0 OR GPL-2.0 WITH Classpath-exception-2.0
 * #L%
 */

import lombok.Builder;
import lombok.Getter;
import lombok.Value;

import java.util.Set;

/**
 * Immutable value object grouping the four JNG-6415 locale settings — {@code principalLocaleAttribute},
 * {@code supportedLanguages} (raw CSV), {@code defaultLanguage}, and {@code browserLanguageCheck} —
 * into a single bundle carried through the runtime's Guice/Spring wiring and consumed identically
 * by {@code DefaultActorResolver} (login-time refresh) and {@code PrincipalLocaleProvider}
 * (per-request read).
 *
 * <p>Before this type existed, the same four values were expressed as 4 dedicated Guice
 * {@code @BindingAnnotation} qualifiers, 4 conditional {@code bind(...).toInstance(...)} calls in
 * the Guice module, and 3–4 {@code @Value("${judo.platform.…}")} parameters duplicated across two
 * Spring {@code @Bean} methods — one logical bundle expressed 3× and consumed 2×. Collapsing them
 * here reduces the touch-surface for adding a fifth locale setting to ≤ 2 files (this class plus
 * the app-facing {@code JudoDefaultModuleConfiguration}).
 *
 * <p>The parsed supported-language set is memoized via Lombok {@code @Getter(lazy = true)} — the
 * CSV is split into a {@link Set} exactly once per JVM (both wiring frameworks singleton-scope
 * this object), instead of on every {@code PrincipalLocaleProvider} construction as before.
 */
@Value
@Builder
public class PrincipalLocaleConfig {

    /**
     * Mapped, non-transient actor attribute holding the user's BCP-47 locale. When null, empty, or
     * whitespace-only the feature is disabled ({@link #isEnabled()} returns {@code false}) and every
     * consumer treats the runtime as if JNG-6415 were never turned on.
     */
    String principalLocaleAttribute;

    /**
     * Comma-separated BCP-47 tags this deployment offers, verbatim as configured. Parsing is
     * deferred to {@link #getParsedSupportedLanguages()} so the split runs at most once.
     */
    String supportedLanguages;

    /** Terminal fallback and precedence floor; null/blank defers to {@code PrincipalLocaleResolver}'s own default. */
    String defaultLanguage;

    /**
     * When {@code true} (the default), the request {@code Accept-Language} header is the top
     * precedence tier for authenticated logins and drives anonymous request resolution. Explicit
     * {@code false} disables both.
     */
    @Builder.Default
    Boolean browserLanguageCheck = Boolean.TRUE;

    /**
     * Parse-once view of {@link #supportedLanguages} using
     * {@link PrincipalLocaleResolver#parseSupportedLanguages(String)}. Memoized (thread-safe
     * double-checked lock generated by Lombok) so the singleton wiring parses exactly once.
     */
    @Getter(lazy = true)
    Set<String> parsedSupportedLanguages =
            PrincipalLocaleResolver.parseSupportedLanguages(supportedLanguages);

    /**
     * Feature gate: {@code true} iff {@link #principalLocaleAttribute} is non-blank. Consumers use
     * this instead of duplicating the blank-check.
     */
    public boolean isEnabled() {
        return principalLocaleAttribute != null && !principalLocaleAttribute.trim().isEmpty();
    }
}
