<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<parent>
		<groupId>hu.blackbelt.judo.runtime</groupId>
		<artifactId>judo-runtime-core-parent</artifactId>
		<version>${revision}</version>
	</parent>

	<artifactId>judo-runtime-core</artifactId>
	<packaging>bundle</packaging>

	<name>JUDO Runtime Core :: Core</name>

	<build>
		<plugins>
			<plugin>
				<groupId>org.apache.felix</groupId>
				<artifactId>maven-bundle-plugin</artifactId>
				<configuration>
					<instructions>
						<Export-Package>hu.blackbelt.judo.runtime.core.*;version=${project.version}</Export-Package>
					</instructions>
				</configuration>
			</plugin>

			<plugin>
				<artifactId>maven-dependency-plugin</artifactId>
				<executions>
					<execution>
						<goals>
							<goal>properties</goal>
						</goals>
					</execution>
				</executions>
			</plugin>

			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-surefire-plugin</artifactId>
				<configuration>
					<argLine>${jacoco.agent} -Dfile.encoding=UTF-8
						--add-opens java.base/java.lang=ALL-UNNAMED
						--add-opens java.base/java.util=ALL-UNNAMED
						--add-opens java.base/java.time=ALL-UNNAMED
						-javaagent:${com.ginsberg:junit5-system-exit:jar}</argLine>
				</configuration>
			</plugin>
		</plugins>
		<pluginManagement>
			<plugins>
				<!--This plugin's configuration is used to store Eclipse m2e settings only. It has no influence on the Maven build itself.-->
				<plugin>
					<groupId>org.eclipse.m2e</groupId>
					<artifactId>lifecycle-mapping</artifactId>
					<version>1.0.0</version>
					<configuration>
						<lifecycleMappingMetadata>
							<pluginExecutions>
								<pluginExecution>
									<pluginExecutionFilter>
										<groupId>
											org.codehaus.mojo
										</groupId>
										<artifactId>
											flatten-maven-plugin
										</artifactId>
										<versionRange>
											[1.1.0,)
										</versionRange>
										<goals>
											<goal>flatten</goal>
										</goals>
									</pluginExecutionFilter>
									<action>
										<ignore></ignore>
									</action>
								</pluginExecution>
							</pluginExecutions>
						</lifecycleMappingMetadata>
					</configuration>
				</plugin>
			</plugins>
		</pluginManagement>
	</build>


	<dependencyManagement>
		<dependencies>
			<dependency>
				<groupId>hu.blackbelt.judo.runtime</groupId>
				<artifactId>judo-runtime-core-dependencies</artifactId>
				<type>pom</type>
				<scope>import</scope>
				<version>${project.version}</version>
			</dependency>
		</dependencies>
	</dependencyManagement>

	<dependencies>
		<dependency>
			<groupId>javax.validation</groupId>
			<artifactId>validation-api</artifactId>
		</dependency>

		<dependency>
			<groupId>hu.blackbelt.judo</groupId>
			<artifactId>judo-dao-api</artifactId>
		</dependency>

		<dependency>
			<groupId>hu.blackbelt.mapper</groupId>
			<artifactId>mapper-api</artifactId>
		</dependency>

		<dependency>
			<groupId>hu.blackbelt.mapper</groupId>
			<artifactId>mapper-impl</artifactId>
		</dependency>

		<!--
		<dependency>
			<groupId>org.junit-pioneer</groupId>
			<artifactId>junit-pioneer</artifactId>
			<version>2.3.0</version>
			<scope>test</scope>
		</dependency>
		-->
		<dependency>
			<groupId>uk.org.webcompere</groupId>
			<artifactId>system-stubs-core</artifactId>
			<version>2.1.7</version>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>uk.org.webcompere</groupId>
			<artifactId>system-stubs-jupiter</artifactId>
			<version>2.1.7</version>
			<scope>test</scope>
		</dependency>

		<dependency>
			<groupId>com.ginsberg</groupId>
			<artifactId>junit5-system-exit</artifactId>
			<version>2.0.2</version>
			<scope>test</scope>
		</dependency>

	</dependencies>
</project>
